import Product_1 from "../../public/images/product-1.png";
import Product_2 from "../../public/images/product-2.png";
import Product_3 from "../../public/images/product-3.png";
import Product_4 from "../../public/images/product-4.png";
import Product_5 from "../../public/images/product-5.png";
import Product_6 from "../../public/images/product-6.png";

export const products = [
  {
    id: "1",
    name: "Pistachios",
    category: "Pistachios",
    price: "₹350", // base price for 250g
    sizes: ["250gm", "500gm", "1kg", "2kg"],
    desc: "Exquisite pistachios lightly salted for a perfect balance of taste and nutrition. Great for parties, snacks, or as a topping.",
    image: Product_1,
    nutrition: "Good source of fiber, iron, and antioxidants.",
    ingredients: "100% Pistachios, Salt",
    origin: "Iran",
    shelfLife: "12 months",
    storage: "Keep in a cool, dry place. Refrigerate for longer freshness.",
  },
  {
    id: "2",
    name: "Walnuts",
    category: "Walnuts",
    price: "₹280",
    sizes: ["250gm", "500gm", "1kg", "2kg"],
    desc: "Superior quality walnuts known for their rich flavor and nutritional benefits. Excellent for brain health.",
    image: Product_2,
    nutrition: "Omega-3 rich, supports brain and heart health.",
    ingredients: "100% Kashmiri Walnuts",
    origin: "Kashmir, India",
    shelfLife: "12 months",
    storage: "Store in a cool, dry place or refrigerate for extended shelf life.",
  },
  {
    id: "3",
    name: "Almonds",
    category: "Almonds",
    price: "₹350",
    sizes: ["250gm", "500gm", "1kg", "2kg"],
    desc: "Premium quality almonds roasted to perfection for a crunchy texture and enhanced flavor. Ideal for healthy snacking and baking.",
    image: Product_3,
    nutrition: "Rich in Vitamin E and antioxidants.",
    ingredients: "100% Roasted Almonds",
    origin: "California, USA",
    shelfLife: "12 months",
    storage: "Keep in a cool, dry place. Refrigerate for longer freshness.",
  },
  {
    id: "4",
    name: "Dates",
    category: "Dates",
    price: "₹180",
    sizes: ["250gm", "500gm", "1kg", "2kg"],
    desc: "Juicy, soft dates, naturally sweet and packed with energy. Perfect for breakfast or as a healthy snack.",
    image: Product_4,
    nutrition: "Excellent source of energy and iron.",
    ingredients: "100% Arabian Dates",
    origin: "Saudi Arabia",
    shelfLife: "24 months",
    storage: "Keep in a cool, dry place. Once opened, store in an airtight container.",
  },
  {
    id: "5",
    name: "Cashews",
    category: "Cashews",
    price: "₹325",
    sizes: ["250gm", "500gm", "1kg", "2kg"],
    desc: "Delicious, crunchy cashews sourced from the finest farms. Perfect for snacking, cooking, or gifting. Rich in healthy fats and proteins.",
    image: Product_5,
    nutrition: "High in protein, healthy fats, and magnesium.",
    ingredients: "100% Premium Cashews",
    origin: "India",
    shelfLife: "12 months",
    storage: "Store in a cool, dry place away from direct sunlight.",
  },
  {
    id: "6",
    name: "Raisins",
    category: "Raisins",
    price: "₹170",
    sizes: ["250gm", "500gm", "1kg", "2kg"],
    desc: "Plump, sweet raisins without seeds, perfect for baking, trail mixes, or as a natural sweetener in dishes.",
    image: Product_6,
    nutrition: "Natural sugar and potassium-rich.",
    ingredients: "100% Seedless Golden Raisins",
    origin: "Turkey",
    shelfLife: "18 months",
    storage: "Store in a cool, dry place in an airtight container.",
  },
];
